title: 记录创业、投资及成长的思考
description: 何太极老师的个人频道，在这里分享创业投资、个人成长、读书和认知科学
author: 何太极
github: www.airwe.com
about:  致力于使人们更加自由的事情。
disqus_shortname: bbihyq
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/he.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:


share:
  twitter_username: bbihyq
  fb_appid: 1749788565247320

urls:
    - text: 关于
      url: /about/
    - text: 资源
      url: http://www.bukop.com/
    - text: 微博
      url: https://weibo.com/u/6564566407
    - text: 推特
      url: https://twitter.com/allindefi

url: "https://www.airwe.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
